// Dados da aplicação. Cada entrada: { id, title, desc, quote?, tag }
// Tags válidas: games | música | cinema | séries | dub | tech

const items = [
  {
    id: 1,
    title: "Trilha do Tarzan — Phil Collins",
    desc: 'Chamaram o Phil Collins pra fazer musiquinha de selva. Ele ganhou Oscar, cantou em 5 idiomas, e "Son of Man" te faz querer ser uma pessoa melhor. Pra um filme de homem-macaco.',
    quote: { text: "I just felt the emotion of the story and wrote from that.", author: "Phil Collins, provavelmente sobre compor pra um homem-macaco" },
    tag: "música",
  },
  {
    id: 2,
    title: '"Megalovania" — Undertale',
    desc: "Toby Fox fez praticamente sozinho uma música de 2 minutos que virou hino global de um jogo indie de RPG feito por uma pessoa.",
    quote: { text: "Fiz o jogo inteiro sozinho. A música também.", author: "Toby Fox, provavelmente one-man army" },
    tag: "música",
  },
  {
    id: 3,
    title: "Abertura de Up",
    desc: "10 minutos sem diálogo que destroem emocionalmente qualquer ser humano. E é só a introdução do filme.",
    quote: { text: "Se o público não amar os personagens, eles não embarcam na viagem.", author: "Pete Docter, diretor, sobre 10 minutos que destroem adultos" },
    tag: "cinema",
  },
  {
    id: 4,
    title: "Spider-Man: Across the Spider-Verse",
    desc: "Cada frame dá pra emoldurar. Era pra ser desenho da Sony, virou galeria de arte em movimento.",
    quote: { text: "Every frame of this movie could be a poster.", author: "Praticamente todo review que existe" },
    tag: "cinema",
  },
  {
    id: 5,
    title: '"Let It Go" — Frozen',
    desc: "Música de Broadway de nível profissional num filme infantil da Disney. Podia ter sido musiquinha qualquer, virou hit mundial.",
    quote: { text: "The cold never bothered me anyway.", author: "Elsa, traumatizando pais no karaokê até hoje" },
    tag: "música",
  },
  {
    id: 6,
    title: "A comida em Ratatouille",
    desc: "Comida animada que parece mais apetitosa que comida de verdade. É crime contra a realidade.",
    quote: { text: "Anyone can cook.", author: "Chef Gusteau, um rato concordou" },
    tag: "cinema",
  },
  {
    id: 7,
    title: "Comida em filmes do Studio Ghibli",
    desc: "Cada cena de comida no Ghibli é projetada pra te dar fome às 3 da manhã. O ramen do Ponyo, o bacon com ovo do Howl, o bentô do Totoro. São desenhos pra criança e a comida parece mais gostosa que qualquer foto de restaurante 5 estrelas. Miyazaki anima comida como se fosse um ato de amor. Porque é.",
    quote: { text: "Comida é uma forma de expressar amor sem palavras.", author: "Hayao Miyazaki, provavelmente fazendo gente chorar com bacon frito" },
    tag: "cinema",
  },
  {
    id: 8,
    title: "Arcane",
    desc: "Baseado em League of Legends. Entregaram animação, trilha, roteiro e atuação no nível de melhor série do ano. Tão boa que deu origem ao meme: 'animação incrível, deviam fazer um jogo baseado nela'. O jogo veio primeiro. O LoL virou nota de rodapé do próprio filho.",
    quote: { text: "Is there anything so undoing as a daughter?", author: "Silco, provavelmente vilão de jogo de MOBA fazendo gente chorar" },
    tag: "séries",
  },
  {
    id: 9,
    title: "Animação de Jujutsu Kaisen",
    desc: "As notas de direção da MAPPA parecem um livro de documentação técnica — o nível de detalhismo é absurdo. Cada frame de luta é obra de arte. Animadores provavelmente não viram a família por meses pra entregar sakuga desse nível num anime semanal de shounen. Não precisava ser tão bom. Mas foi.",
    quote: { text: "Os animadores colocaram suas vidas nessas cenas.", author: "Fãs, provavelmente entre admiração e preocupação com crunch" },
    tag: "séries",
  },
  {
    id: 10,
    title: "Violet Evergarden — animação da KyoAni",
    desc: "Anime sobre uma garota escrevendo cartas. A Kyoto Animation tratou como o projeto mais importante da história da animação. Cada frame parece pintura a óleo — água, cabelo, luz, expressões, tudo no nível de filme de cinema. Mas você não consegue apreciar a animação porque tá chorando demais pra enxergar a tela. Não precisava ser tão bonito. Não precisava doer tanto.",
    quote: { text: "Eu quero saber o que 'eu te amo' significa.", author: "Violet Evergarden, destruindo adultos com uma frase" },
    tag: "séries",
  },
  {
    id: 11,
    title: "Animação de Demon Slayer — o trem",
    desc: "A Ufotable fez uma locomotiva 3D tão bem integrada que parecia 2D. Tão bem feita que na abertura do filme botaram o trem GIRANDO só pra provar que era modelagem 3D e não desenho. Quando você precisa convencer a audiência de que sua animação NÃO é 2D porque ficou boa demais, você foi longe demais. E sim, o trem é literalmente um trem. Sou mineiro.",
    quote: { text: "Espera, isso é 2D? Isso é 3D? O que tá acontecendo?", author: "Todo espectador na cena do trem, provavelmente" },
    tag: "cinema",
  },
  {
    id: 12,
    title: "Just Dance 2026 — Born to Be Alive (stop motion)",
    desc: "Jogo de dançar na sala com a família. O estúdio Inspira de Valencia construiu puppets artesanais, cenários à mão, e animou QUADRO A QUADRO quase 3 minutos de stop motion puro usando rotoscopia da coreografia real. Pra um NÍVEL de Just Dance. Ninguém ia reclamar de um bonequinho 3D genérico. Eles fizeram arte.",
    quote: { text: "Construímos os personagens e vários cenários à mão. Foi incrivelmente desafiador.", author: "Inspira Stop Motion, provavelmente" },
    tag: "games",
  },
  {
    id: 13,
    title: "Coringa do Heath Ledger",
    desc: "Filme de super-herói, 2008. Ele decidiu que ia ganhar Oscar póstumo e ganhou. Num filme do Batman.",
    quote: { text: "Why so serious?", author: "Heath Ledger, numa performance que ninguém esqueceu" },
    tag: "cinema",
  },
  {
    id: 14,
    title: "Joker (2019) — Joaquin Phoenix",
    desc: "Filme de vilão de HQ que ganhou Leão de Ouro em Veneza e Oscar de Melhor Ator. Era pra ser filme de super-herói e virou estudo de personagem que compete com Taxi Driver. Dois Coringas diferentes, dois Oscars. O personagem não precisava ser tão bom DUAS VEZES.",
    quote: { text: "I used to think that my life was a tragedy, but now I realize, it's a comedy.", author: "Arthur Fleck, num filme que não precisava existir e mudou o cinema" },
    tag: "cinema",
  },
  {
    id: 15,
    title: "Robert Downey Jr. como Homem de Ferro (2008)",
    desc: "Ator que Hollywood descartou. Saiu de clínica de reabilitação, era inassegurável — literalmente nenhuma seguradora cobria ele num filme. A Marvel, também quase falida, apostou tudo no primeiro filme que produzia sozinha e escalou o cara que ninguém queria. Dois azarões sem nada a perder. Resultado: nascimento do MCU, a franquia mais lucrativa da história do cinema. Um renascimento pessoal que renasceu um universo inteiro.",
    quote: { text: "I am Iron Man.", author: "Tony Stark, improvisado por RDJ — a frase que iniciou o MCU" },
    tag: "cinema",
  },
  {
    id: 16,
    title: "Barbie (2023)",
    desc: "Filme de boneca da Mattel. Deveria ter sido comercial de 2 horas. Greta Gerwig entregou comentário social, feminismo, crise existencial, e Ryan Gosling fazendo a performance da carreira dele como Ken. He was Kenough. Nós todos somos Kenough.",
    quote: { text: "He's just Ken.", author: "Toda a humanidade, aceitando essa verdade" },
    tag: "cinema",
  },
  {
    id: 17,
    title: "Piratas do Caribe: A Maldição do Pérola Negra (2003)",
    desc: "Filme baseado em BRINQUEDO DE PARQUE. A Disney falou 'faz um filme daquela atração de barquinho'. Johnny Depp apareceu fazendo Keith Richards pirata e entregou uma das performances mais icônicas do cinema. Indicação ao Oscar de Melhor Ator por interpretar pirata de parque temático. Só não ganhou mais porque 2003 foi o ano que Senhor dos Anéis limpou 11 Oscars.",
    quote: { text: "Mas por que o rum acabou?", author: "Jack Sparrow, personagem de atração de parque que virou ícone cultural" },
    tag: "cinema",
  },
  {
    id: 18,
    title: "The Lego Movie (2014)",
    desc: "Comercial de brinquedo de 2 horas. Entregou crítica social contra consumismo, conformismo e controle corporativo — ENQUANTO VENDE O PRODUTO. 'Everything is Awesome' é a música mais grudenta do planeta E uma sátira sobre conformismo cego ao mesmo tempo. O filme te critica por comprar Lego enquanto te faz querer comprar Lego. Cavalo de Troia mais caro da história do marketing.",
    quote: { text: "Everything is awesome! Everything is cool when you're part of a team!", author: "Hino do conformismo disfarçado de música feliz" },
    tag: "cinema",
  },
  {
    id: 19,
    title: "Shrek (2001) — o projeto 'Gulag'",
    desc: "Na DreamWorks, animadores que irritavam Katzenberg eram mandados pro Shrek como CASTIGO. O projeto era chamado de 'the Gulag' e ser transferido pra lá era 'being Shreked'. Budget de $20 milhões, limite de 17 personagens, equipe de recém-formados. O time de punição fez o filme que ganhou o primeiro Oscar de Animação da história e virou fenômeno cultural global. De castigo a Cannes com ovação de pé.",
    quote: { text: "Era o Gulag. Se você falhava no Príncipe do Egito, era mandado pro Shrek.", author: "Animador da DreamWorks, do livro Men Who Would Be King" },
    tag: "cinema",
  },
  {
    id: 20,
    title: "O Príncipe do Egito (1998)",
    desc: "A DreamWorks botou o TIME A aqui — os melhores animadores. Gastaram tudo. A cena do Mar Vermelho abrindo é uma das sequências de animação mais impressionantes já feitas. 'When You Believe' ganhou Oscar. Fracasso comercial relativo pro orçamento, mas a animação é tão absurda que impressiona até hoje. O time B deles fez o Shrek. O time A fez isso. Os dois não precisavam ser tão bons.",
    quote: { text: "Thus saith the Lord.", author: "Moisés, numa cena de animação que compete com qualquer filme live-action" },
    tag: "cinema",
  },
  {
    id: 21,
    title: "Dublagem do Shrek PT-BR — Bussunda",
    desc: "Bussunda elevou o personagem. Em alguns momentos é melhor que o original, e o original já é obra-prima.",
    quote: { text: "Cebolas têm camadas! Ogros têm camadas!", author: "Bussunda como Shrek, ensinando filosofia pra um burro" },
    tag: "dub",
  },
  {
    id: 22,
    title: "Guilherme Briggs — Coisas Demais",
    desc: "Jack Sparrow. Gênio do Aladdin. Deadpool. Optimus Prime. O cara dubla TUDO e tudo fica melhor do que precisava. Dublar Robin Williams improvisando é traduzir caos puro em tempo real. Capturar Johnny Depp bêbado é quase impossível. Ele fez os dois parecerem naturais. Não é um dublador, é um patrimônio nacional que ainda não recebeu a medalha.",
    quote: { text: "Ao infinito e além! / Eu sou o Deadpool! / Autobots, transformar!", author: "Guilherme Briggs, sendo 47 personagens ao mesmo tempo" },
    tag: "dub",
  },
  {
    id: 23,
    title: "Tropa de Elite (2007)",
    desc: "Num mar de filme brasileiro genérico sobre droga, tráfico e violência... sai um filme brasileiro INCRÍVEL sobre... droga, tráfico e violência. Mesmos ingredientes, resultado completamente diferente. Wagner Moura fez o Capitão Nascimento tão icônico que gente que nunca viu o filme cita ele. Depois foi fazer Narcos — sobre drogas e violência de novo. O cara tem um tipo.",
    quote: { text: "Pede pra sair! PEDE PRA SAIR!", author: "Capitão Nascimento, virando patrimônio cultural brasileiro" },
    tag: "cinema",
  },
  {
    id: 24,
    title: '"We Are Number One" — LazyTown',
    desc: "Música de vilão de programa infantil islandês. Quando você escuta com atenção, é genuinamente uma composição MUITO boa.",
    tag: "música",
  },
  {
    id: 25,
    title: "Cabelo da Merida — Valente",
    desc: "A Pixar criou um software inteiro só pra simular aquele cabelo ruivo cacheado. Só pra uma personagem.",
    quote: { text: "Construímos um simulador inteiro só pra aquele cabelo.", author: "Equipe da Pixar, provavelmente sobre criar software pra uma personagem" },
    tag: "cinema",
  },
  {
    id: 26,
    title: "Trilhas incidentais do Chaves",
    desc: "Nenhuma daquelas músicas foi composta pro programa. Eles só souberam escolher tão bem que viraram trilha oficial do humor brasileiro.",
    quote: { text: "A gente nem compôs. A gente só escolheu bem.", author: "O programa mais brasileiro que não é brasileiro, provavelmente" },
    tag: "música",
  },
  {
    id: 27,
    title: '"Evidências"',
    desc: "Começa como balada romântica, vira hino nacional do karaokê. Quando você analisa a estrutura, é uma obra-prima de composição pop-sertaneja. Não precisavam ter entregado tanto.",
    quote: { text: "Quando eu digo que deixei de te amar...", author: "Todo brasileiro, provavelmente gritando no karaokê às 2 da manhã" },
    tag: "música",
  },
  {
    id: 28,
    title: "NPCs do RDR2",
    desc: "Cada pessoa aleatória tem rotina de sono, profissão, opinião sobre você. Ninguém vai NPC-caçar pra ver isso. A Rockstar fez assim mesmo.",
    quote: { text: "We wanted every part of the world to feel alive.", author: "Rockstar Games, provavelmente levando 'alive' literalmente demais" },
    tag: "games",
  },
  {
    id: 29,
    title: "Detalhes anatômicos dos cavalos no RDR2",
    desc: "A Rockstar programou a anatomia dos cavalos pra reagir dinamicamente ao clima. Ninguém pediu. Ninguém ia notar. Fizeram assim mesmo. Você sabe do que eu tô falando.",
    quote: { text: "Sim, reagem ao frio. Era importante pra gente.", author: "Dev anônimo da Rockstar, provavelmente" },
    tag: "games",
  },
  {
    id: 30,
    title: "Elton John no Rei Leão",
    desc: '"Circle of Life" abre o filme e em 4 minutos te faz chorar por um leão bebê que você acabou de conhecer. O cara que se veste como trio elétrico de Salvador compôs um hino religioso.',
    quote: { text: "Eu chorei compondo Can You Feel the Love Tonight. Pra dois leões.", author: "Elton John, provavelmente de óculos com glitter" },
    tag: "música",
  },
  {
    id: 31,
    title: "Eminem em 8 Mile",
    desc: 'Era pra ser filme de rapper. Ele simplesmente... atuou. Cenas silenciosas, introspectivas. "Lose Yourself" foi o primeiro rap a ganhar Oscar. Ele não foi receber porque tava EM CASA DORMINDO com desenho ligado pra filha Hailie. Não assistiu a cerimônia. Não achou que ia ganhar. Luis Resto foi aceitar por ele. O cara farma aura dormindo.',
    quote: { text: "I was just at home with my daughter. Hailie had to be at school early in the morning, so I was sleeping.", author: "Eminem, sobre a noite que ganhou o Oscar" },
    tag: "cinema",
  },
  {
    id: 32,
    title: "Kim Basinger como mãe do Eminem",
    desc: "Atriz vencedora do Oscar aceitou fazer a mãe bêbada do Eminem num filme de rap. E entregou.",
    quote: { text: "Eu li o roteiro e pensei: preciso fazer isso.", author: "Kim Basinger, provavelmente ganhadora do Oscar, aceitando ser mãe do Eminem" },
    tag: "cinema",
  },
  {
    id: 33,
    title: 'Goofy Movie — "Stand Out" e "I2I"',
    desc: "Filme direto pra vídeo sobre Pateta constrangendo o filho. O compositor fez o Prince fictício do universo Disney com músicas funk/pop perfeitas.",
    quote: { text: "Stand out above the crowd!", author: "Powerline, o artista fictício mais real que muito real" },
    tag: "música",
  },
  {
    id: 34,
    title: "Goofy Movie — cena do Pateta vulnerável",
    desc: '"Eu só queria fazer parte dela." Um cachorro de desenho animado direto-pra-vídeo de 1995 fez mais pela masculinidade saudável que décadas de psicologia pop.',
    quote: { text: "I was just trying to take my boy fishing.", author: "Pateta, provavelmente destruindo adultos emocionalmente desde 1995" },
    tag: "cinema",
  },
  {
    id: 35,
    title: "GoldenEye 007 (N64)",
    desc: "Jogo de tiro licenciado de filme do James Bond no N64. Ninguém esperava nada. Entregaram o multiplayer split-screen que definiu uma geração inteira. 4 amigos num sofá, tela dividida em 4 quadradinhos minúsculos, e mesmo assim era o melhor jogo de tiro que existia. Inventou o FPS de console e ainda tinha uma música de pausa que era proto-trap antes do trap existir.",
    quote: { text: "No Oddjob.", author: "Regra universal não-escrita de todo sofá nos anos 90" },
    tag: "games",
  },
  {
    id: 36,
    title: "Rare (o estúdio inteiro)",
    desc: "Estúdio britânico operando de uma FAZENDA no interior da Inglaterra. Second party — nem first party eram. Entregaram: Donkey Kong Country (gráficos impossíveis no SNES), GoldenEye, Perfect Dark (FPS melhor que GoldenEye no MESMO hardware), Banjo-Kazooie, Conker's Bad Fur Day (esquilo bêbado com humor adulto no N64), Killer Instinct, Diddy Kong Racing. Tudo de uma fazenda. Um celeiro produziu mais clássicos que estúdios bilionários inteiros.",
    quote: { text: "Era literalmente uma fazenda com computadores.", author: "Descrição real do escritório da Rare nos anos 90, provavelmente" },
    tag: "games",
  },
  {
    id: 37,
    title: "Eternal Darkness: Sanity's Requiem (GameCube)",
    desc: "O demo pro N64 era tão bom que a Nintendo achou que era fake e pediu pra ver o código. Era real. Contrataram o estúdio. O jogo fingia deletar seu save, mostrava tela azul, abaixava o volume, botava insetos na tela. O Sanity System foi PATENTEADO pela Nintendo e por isso nenhum jogo pode fazer aquilo legalmente até hoje. Uma inovação tão boa que foi trancada pra sempre.",
    quote: { text: "Isso é impossível nesse hardware. Mostra o código. — ...é real.", author: "Nintendo, contratando o estúdio na hora" },
    tag: "games",
  },
  {
    id: 38,
    title: "System Shock (1994) — Looking Glass Technologies",
    desc: "Saiu 9 meses depois de Doom e foi esmagado pelo Doom 2 semanas depois. Mas enquanto Doom era 'atira em tudo', System Shock inventou: audio logs como narrativa, inventário grid, ambientes 3D reais, física, gravidade variável, hacking, armas com recarga manual. Tudo que BioShock, Dead Space, Deus Ex, Prey e Dishonored usam veio daqui. O Doom definiu o FPS. O System Shock definiu todo o resto.",
    quote: { text: "Look at you, hacker. A pathetic creature of meat and bone.", author: "SHODAN, a vilã de IA que definiu vilões de IA pra sempre" },
    tag: "games",
  },
  {
    id: 39,
    title: "SHODAN — Terri Brosius, a tecladista",
    desc: "Uma das vilãs mais icônicas da história dos games foi dublada por uma TECLADISTA de banda de rock de Boston. Terri Brosius tocava na banda Tribe, a banda acabou, ela entrou na Looking Glass como funcionária. O estúdio usou empregados pra gravar vozes porque não tinha budget pra atores. A mina do teclado criou a voz de IA mais aterrorizante do gaming. Não era dubladora. Era a tecladista que tava no escritório. INSECT.",
    quote: { text: "You move like an insect. You think like an insect. You ARE an insect.", author: "SHODAN, dublada por uma tecladista de rock que tava no escritório" },
    tag: "games",
  },
  {
    id: 40,
    title: "Silent Hill (1999) — Team Silent",
    desc: "O Team Silent era o time dos 'sobras' da Konami — devs que a empresa não sabia o que fazer. Jogaram eles num projeto pra competir com Resident Evil. Inventaram o terror psicológico em games. O nevoeiro icônico? Era porque o PS1 não renderizava distância. Limitação técnica virou gênio artístico. Tenta achar uma review de survival horror que não menciona esse jogo. I dare you.",
    quote: { text: "Nós não éramos o time principal. Éramos os que sobraram.", author: "Membros do Team Silent, provavelmente sobre criar uma obra-prima por acidente" },
    tag: "games",
  },
  {
    id: 41,
    title: "Metal Gear Solid 3: Snake Eater (2004)",
    desc: "Gráfico de PS3 em 32MB de RAM. Camuflagem que muda com o ambiente, você caça e come animais, fica doente de comida podre, trata ferimentos específicos, joga cobra na cara do inimigo, e se esperar UMA SEMANA real no boss do The End ele MORRE DE VELHICE. É TDAH made manifest e é glorioso. Tudo isso em 32 megas. Uma foto de celular hoje pesa mais que a RAM inteira que rodava esse jogo.",
    quote: { text: "What a thrill...", author: "Snake Eater, a abertura que ninguém skipava" },
    tag: "games",
  },
  {
    id: 42,
    title: "Final Fantasy XII (2006) — o PS2 tendo um AVC",
    desc: "Mundo aberto sem loading, centenas de inimigos, voice acting completo, combate em TEMPO REAL, em 32MB de RAM. E o Gambit System: você PROGRAMAVA a IA dos seus personagens com lógica IF-THEN. Fóruns ensinavam 'builds' como se fosse linguagem de programação. Só faltou curso na Udemy. O barramento do Graphics Synthesizer era ~48GB/s — a Square explorou isso regenerando texturas A CADA FRAME. Tá ouvindo seu PS2 chorando? É ele regenerando tudo do zero 30 vezes por segundo. Falta de educação técnica.",
    quote: { text: "I'm Captain Basch fon Ronsenburg of Dalmasca!", author: "Vaan, gritando voice acted num console de 32MB" },
    tag: "games",
  },
  {
    id: 43,
    title: "Gato de Botas 2: O Último Pedido",
    desc: "Spin-off de franquia morta do Shrek. Entregaram um filme sobre mortalidade e ansiedade com o melhor vilão da década. O protagonista tem ataque de pânico de verdade. Num filme infantil.",
    quote: { text: "Eu não temo você.", author: "Gato de Botas pro Lobo/Morte, provavelmente no filme que não precisava existir" },
    tag: "cinema",
  },
  {
    id: 44,
    title: 'Bo Burnham: Inside — "Welcome to the Internet"',
    desc: "Comediante trancado num quarto na pandemia. Era pra ser especial de comédia. Virou álbum conceitual + filme experimental + terapia coletiva.",
    quote: { text: "Welcome to the internet, have a look around.", author: "Bo Burnham, sozinho num quarto, fazendo Broadway" },
    tag: "música",
  },
  {
    id: 45,
    title: 'Interstellar — "No Time for Caution"',
    desc: "Hans Zimmer fez música de órgão de igreja em camadas pra uma cena de nave acoplando em outra nave. 4 minutos de catarse sonora pra uma manobra de engenharia.",
    quote: { text: "It's not possible. — No. It's necessary.", author: "Cooper, acoplando ao som de órgão de igreja" },
    tag: "música",
  },
  {
    id: 46,
    title: "Avatar: A Lenda de Aang",
    desc: "Desenho da Nickelodeon que tratou genocídio, trauma de guerra, ditadura e luto com mais cuidado que 90% dos dramas adultos. Era pra vender boneco.",
    quote: { text: "That's rough, buddy.", author: "Zuko, sobre a namorada virar a lua" },
    tag: "séries",
  },
  {
    id: 47,
    title: "Teen Titans (2003)",
    desc: "Desenho da Cartoon Network pra vender boneco. Entregaram arcos narrativos do nível de anime japonês — Terra, Trigon, Slade — tudo PESADO pra desenho de criança. Animação absurda, até os figurantes tinham design impecável. Tinha abertura EM JAPONÊS. Na Cartoon Network americana. Ninguém pediu.",
    quote: { text: "Things change, Beast Boy. The girl you want me to be is just a memory.", author: "Terra, destruindo crianças emocionalmente num sábado de manhã" },
    tag: "séries",
  },
  {
    id: 48,
    title: "Wall-E — primeiros 40 minutos",
    desc: "Filme infantil com quase zero diálogo na primeira metade. Uma história de amor entre dois robôs contada só por gesto e som. Chaplin + Kubrick pra criança.",
    quote: { text: "E se fizéssemos um filme infantil sem diálogo por 40 minutos?", author: "Andrew Stanton, provavelmente apostando que criança aguenta Kubrick" },
    tag: "cinema",
  },
  {
    id: 49,
    title: 'Cowboy Bebop — abertura "Tank!"',
    desc: "Anime de 1998. Yoko Kanno fez big band jazz com metais e baixo acústico que parece trilha do Tarantino. Toca 1 minuto e meio por episódio e ainda é a melhor abertura de anime já feita.",
    quote: { text: "See you, Space Cowboy...", author: "Cartão final de cada episódio, eternamente" },
    tag: "música",
  },
  {
    id: 50,
    title: "Abertura de Noragami — Goya no Machiawase",
    desc: "Anime sobre um Deus mendigo que rabisca o próprio número em paredes de banheiro público pra conseguir bico por 5 ienes. A abertura trata ele como se fosse o protagonista mais épico da história do anime. Hello Sleepwalkers entregaram um rock tão intenso que você esquece que o personagem é literalmente um sem-teto divino.",
    quote: { text: "Faço qualquer trabalho por apenas 5 ienes!", author: "Yato, Deus mendigo com abertura de Deus supremo" },
    tag: "música",
  },
  {
    id: 51,
    title: "Mad Max: Fury Road",
    desc: "George Miller tinha 70 anos. Entregou o melhor filme de ação já feito com zero CGI, carros reais explodindo na Namíbia, subtexto feminista, e 6 Oscars técnicos. São 2 horas de perseguição de carro.",
    quote: { text: "Oh, what a day! What a lovely day!", author: "Nux, coberto de tinta cromada" },
    tag: "cinema",
  },
  {
    id: 52,
    title: "Assassin's Creed Black Flag",
    desc: "Era pra ser jogo de assassino com temática pirata. Entregaram o melhor simulador de pirata já feito. Navegação, batalhas navais, shanties que a tripulação canta. O cara comprou pra jogar de capuz e saiu querendo ser capitão.",
    quote: { text: "In a world without gold, we might have been heroes.", author: "Edward Thatch/Barba Negra" },
    tag: "games",
  },
  {
    id: 53,
    title: "Baldur's Gate 3 (2023)",
    desc: "A Wizards of the Coast, que não conseguiu fazer a própria 4ª edição de D&D direito, deu a licença pra um estúdio belga. A Larian entregou o Jogo do Ano, ganhou tudo que existia pra ganhar, e fez a melhor propaganda que D&D já teve. A dona da IP não fez — terceirizou e saiu obra-prima.",
    quote: { text: "Faz um joguinho aí com nossa propriedade intelectual. — Jogo do Ano.", author: "Wizards of the Coast vs Larian Studios, provavelmente" },
    tag: "games",
  },
  {
    id: 54,
    title: "O Êxodo da Ubisoft — Expedition 33 + Dispatch",
    desc: "Devs saíram da Ubisoft porque estavam entediados. Um fundou estúdio de 34 pessoas (e um cachorro) e fez o jogo mais premiado da história do The Game Awards. Outros trabalhavam num Splinter Cell que virou XDefiant e morreu em 1 ano — saíram, quase faliram, e venderam 2 milhões. Enquanto isso a Ubisoft tá quase sendo comprada. O CEO chorando provavelmente.",
    quote: { text: "Mandamos embora os criadores de Expedition 33 e Dispatch.", author: "CEO da Ubisoft, chorando provavelmente" },
    tag: "games",
  },
  {
    id: 55,
    title: "PlayStation 2",
    desc: "Era um videogame. 32MB de RAM. TRINTA E DOIS. O Emotion Engine tinha duas unidades vetoriais que você tinha que programar MANUALMENTE — não era programar, era LUTAR contra o hardware. Pesadelo pra devs. Mas o trem fazia TUDO: jogava DVD, rodava Linux, e a Força Aérea dos EUA montou um supercomputador com 1760 unidades. Console mais vendido da história com 155 milhões de unidades, durou 13 anos no mercado. 32MB. O MGS3 rodou em 32MB. Pensa nisso.",
    quote: { text: "It's a computer system that just happens to play games.", author: "Ken Kutaragi, provavelmente pai do PlayStation" },
    tag: "tech",
  },
  {
    id: 56,
    title: "Microsoft Excel",
    desc: "Era pra ser planilha de somar número. Saiu com linguagem de programação Turing-completa, pivot tables, macros, engine de gráfico — tecnologia que nem tinha nome na época. Metade dos negócios do mundo roda em cima de um .xlsx que ninguém tem coragem de mexer. Tem empresa com sistema crítico inteiro em Excel até hoje. Software mais acidentalmente poderoso da história.",
    quote: { text: "DEVELOPERS DEVELOPERS DEVELOPERS DEVELOPERS!", author: "Steve Ballmer, suando no palco como se fosse show de rock" },
    tag: "tech",
  },
  {
    id: 57,
    title: "iPhone (2007)",
    desc: "Os engenheiros do Steve Jobs não reinventaram a roda — inventaram o carro inteiro. Um telefone que matou a câmera compacta, o MP3 player, o GPS, a lanterna, o despertador, o jornal, e meio que a interação humana. Steve Ballmer — o MESMO cara do 'DEVELOPERS' que tá nessa lista — gargalhou na TV: '$500? Nem tem teclado!' Ser humano horrível, ninguém tira isso do Steve. Mas o iPhone mudou a civilização.",
    quote: { text: "$500?! It doesn't have a keyboard! There's no chance that the iPhone is going to get any significant market share.", author: "Steve Ballmer, CEO da Microsoft, 2007. A frase envelheceu como leite." },
    tag: "tech",
  },
  {
    id: 58,
    title: "Steam",
    desc: "Mercado de jogos de PC era ir na loja física, comprar caixa, torcer pra rodar. Gabe Newell fez uma plataforma digital que mudou tudo — wishlist, reviews, workshop, achievements, promoções que destroem carteiras. Tão dominante que toda tentativa de competir vira piada. Uma loja de jogos não precisava ser um ecossistema inteiro. Mas é.",
    quote: { text: "As promoções de Steam são basicamente um serviço público.", author: "Todo gamer com 200 jogos não-jogados na biblioteca, provavelmente" },
    tag: "tech",
  },
  {
    id: 59,
    title: "Linux",
    desc: "Linus Torvalds fez como hobby pra desktop pessoal. 'Just a hobby, won't be big and professional.' Hoje roda: a internet inteira (servidores), Android (maioria dos celulares), TODOS os 500 supercomputadores mais potentes do mundo, carros, TVs, geladeiras, estação espacial, Marte. TUDO. Menos desktop pessoal. O ÚNICO mercado que ele fez pra dominar.",
    quote: { text: "I'm doing a (free) operating system (just a hobby, won't be big and professional).", author: "Linus Torvalds, 1991, no post mais errado e mais certo da história" },
    tag: "tech",
  },
  {
    id: 60,
    title: "TempleOS — o prédio de 30 andares feito por um",
    desc: "Um programador sozinho fez um sistema operacional completo em menos de 30MB: kernel próprio, compilador, linguagem de programação própria (HolyC), gráficos, até simulador de voo. Ruim pra uso diário? Sim. Mas a conquista técnica é como construir um prédio de 30 andares sozinho com as mãos. O prédio pode não ter elevador, mas O CARA FEZ SOZINHO.",
    quote: { text: "It's a 64-bit, non-preemptive multi-tasking, multi-cored, public domain, open source, ring-0-only, single address space, non-networked, PC operating system.", author: "Terry Davis, descrevendo seu trabalho de uma vida" },
    tag: "tech",
  },
  {
    id: 61,
    title: "WinRAR",
    desc: "O modelo de negócio mais confuso e generoso da história. O trial de 40 dias dura 25 anos. Eles confiam tanto na bondade humana que viraram o utilitário padrão do planeta sem nunca te bloquear. É o software 'pago' mais gratuito do mundo.",
    quote: { text: "Please note that WinRAR is not free software...", author: "O aviso que todo mundo ignora há duas décadas" },
    tag: "tech",
  },
  {
    id: 62,
    title: "Devs de codec de vídeo — os heróis invisíveis",
    desc: "Já viu um vídeo no YouTube? Poisé, agradece os bonito. Laurent Aimar, Loren Merritt, Fiona Glaser, Henrik Gramner e outros escrevem codecs (x264, x265, dav1d, ffmpeg) em C e Assembly puro, otimizando instrução SIMD na mão. Sem eles, NADA de vídeo na internet funciona. Zero streaming, zero YouTube, zero Netflix. E o Fabrice Bellard criou o FFmpeg E o QEMU. Uma pessoa.",
    quote: { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds, mas poderia ser qualquer dev de codec respondendo a reclamação" },
    tag: "tech",
  },
  {
    id: 63,
    title: "Minecraft (2011)",
    desc: "Um sueco sozinho fez um jogo de bloquinho feio em Java — é tipo fazer um jogo no Excel. Sem história, sem tutorial, sem objetivo. Jogo mais vendido da história com 300 milhões de cópias. Gerações inteiras aprenderam a programar, arquitetura e sobrevivência por causa de cubos. Rodava a 15 FPS e mesmo assim mudou o mundo.",
    quote: { text: "O jogo não te diz o que fazer. Você decide.", author: "Notch, provavelmente sobre criar liberdade total acidentalmente" },
    tag: "games",
  },
  {
    id: 64,
    title: "Stardew Valley (2016)",
    desc: "Zero estúdios fazendo jogo de fazendinha. ConcernedApe viu o gap e fez TUDO sozinho — arte, música, programação, design, escrita — por 4 anos sendo sustentado pela namorada. Uma pessoa. Todo pixel, toda nota musical, toda linha de diálogo. Vendeu mais de 30 milhões de cópias. A namorada fez o melhor investimento da história dos relacionamentos.",
    quote: { text: "Eu fiz tudo sozinho porque não tinha dinheiro pra contratar ninguém.", author: "ConcernedApe, provavelmente sobre transformar limitação em lenda" },
    tag: "games",
  },
  {
    id: 65,
    title: "No Man's Sky???",
    desc: "Tá na aba de traição também. MAS. Num mundo onde toda empresa lança jogo ruim e foge, a Hello Games calou a boca e entregou updates por 8 anos até o jogo virar exatamente o que prometeram. Ninguém faz isso. É a redenção mais rara da indústria. Merece estar nas duas abas porque a traição foi real mas a redenção também foi.",
    quote: { text: "O silêncio de Sean Murray é a coisa mais alta que um dev já disse.", author: "Internet, provavelmente" },
    tag: "games",
  },
  {
    id: 66,
    title: "ChatGPT / GPT-3.5 (2022)",
    desc: "Um laboratório de pesquisa botou um chatbot no ar e mudou o mundo em semanas. App mais rápido da história a atingir 100 milhões de usuários. De repente todo mundo tinha um 'estagiário de PhD' no bolso. Empresas inteiras mudaram o modelo de negócio. Governos entraram em pânico. Tudo porque alguém falou 'e se a gente deixar as pessoas conversarem com o modelo?'",
    quote: { text: "E se a gente deixar as pessoas conversarem com o modelo?", author: "OpenAI, provavelmente mudando o mundo com uma interface de chat" },
    tag: "tech",
  },
  {
    id: 67,
    title: "DeepSeek — a ironia do 'Open' em OpenAI",
    desc: "A empresa com 'OPEN' no nome fechou tudo — código, pesos, pesquisa. Cobra $200/mês. Aí do outro lado do mundo, de onde ninguém esperava, sai um modelo open source competitivo que sacudiu a indústria inteira. Teve seu momento ao sol. Hoje já não é mais o que era, mas a ironia histórica ninguém apaga: a democratização da IA veio de onde o nome 'open' não tava.",
    quote: { text: "A empresa se chama OpenAI. O modelo aberto veio da China.", author: "A ironia, provavelmente rindo sozinha" },
    tag: "tech",
  },
  {
    id: 68,
    title: "Image Diffusion — movidos a motivação ancestral",
    desc: "Num mundo onde o GPT chora pra gerar um texto com qualidade, os modelos de difusão de imagem geram arte fotorrealista em 4K. Por quê? Porque a motivação humana mais antiga do mundo acelerou o desenvolvimento em 10 anos. VHS venceu Betamax por isso. Internet banda larga explodiu por isso. E agora IA visual é absurdamente avançada pelo mesmo motivo. A humanidade sempre entrega demais quando o incentivo é... ancestral.",
    quote: { text: "A internet é movida por dois combustíveis: curiosidade e hormônios.", author: "A humanidade inteira, provavelmente" },
    tag: "tech",
  },
  {
    id: 69,
    title: "A moto do Kaneda — Akira (1988)",
    desc: "Uma moto de anime. Definiu o que 'moto do futuro' significa PRA SEMPRE. Todo designer de veículo do planeta referencia ela até hoje. A cena do slide virou template universal de 'personagem foda chegando' — Cyberpunk, filmes, jogos, tudo copia. Desenharam um veículo fictício pra um desenho japonês e acidentalmente criaram um ícone de design industrial.",
    quote: { text: "The future is not a straight line.", author: "Katsuhiro Otomo, provavelmente criador do Akira" },
    tag: "cinema",
  },
  {
    id: 70,
    title: "Junji Ito — só Junji Ito",
    desc: "Arte incrívelmente perturbadora de um dos homens mais wholesomes do Japão. Uzumaki, Tomie, Amigara Fault — cada painel é detalhado demais pra existir, horror corporal que dá pesadelo por semanas. E na vida real? Senhor mais fofo do planeta. Ama gatos. Fez um mangá ADORÁVEL sobre os gatos dele. Aparece em entrevista sorrindo, gentil, educado. Aí vai pra casa e desenha espirais consumindo carne humana. A dualidade do homem.",
    quote: { text: "Eu gosto de desenhar coisas assustadoras, mas na vida real sou bem normal.", author: "Junji Ito, provavelmente enquanto acaricia um gato e planeja seu próximo pesadelo" },
    tag: "séries",
  },
  {
    id: 71,
    title: "Hydrogen — Hotline Miami",
    desc: "Jogo indie top-down de pixel sobre matar gente de máscara de galo. O M.O.O.N fez um synth tão hipnótico que te possui em vez de você ouvir. Praticamente criou o synthwave mainstream sozinho. A música de dissociação controlada definitiva.",
    quote: { text: "Eu não componho música. Eu componho estados de dissociação.", author: "M.O.O.N, provavelmente" },
    tag: "música",
  },
  {
    id: 72,
    title: "KPop Demon Hunters (2025)",
    desc: 'O pitch cabe num guardanapo: "girl group de kpop caça demônios". Virou o filme mais assistido da Netflix, ganhou Oscar, fez história na Billboard com 4 músicas no top 10 ao mesmo tempo. A Sony vendeu por troco de pão num deal da pandemia. Custou um pastel e uma coca.',
    quote: { text: "Eu achei que ia ser lixo tentando lucrar com kpop. Eu estava errado.", author: "Basicamente todo review do filme, provavelmente" },
    tag: "cinema",
  },
  {
    id: 73,
    title: "Castlevania (Netflix)",
    desc: "Adaptação de jogo de NES sobre chicotear Drácula. Entregaram uma das melhores séries animadas adultas da década com coreografia de luta que compete com anime japonês e diálogos shakespearianos pro Drácula.",
    quote: { text: "What is a man? A miserable little pile of secrets!", author: "Drácula, no jogo de NES original de 1986" },
    tag: "séries",
  },
  {
    id: 74,
    title: "The Penguin (HBO, 2024)",
    desc: "Spin-off de vilão do Batman. Era pra ser mais conteúdo de DC pra preencher catálogo. Colin Farrell entregou uma das melhores performances de TV da década, irreconhecível debaixo da maquiagem. Cristin Milioti como Sofia Falcone roubou cada cena. Virou basicamente Sopranos em Gotham. Série sobre o PINGUIM não tinha direito de ser tão fenomenal.",
    quote: { text: "Eu não me reconhecia no espelho. Era o Oz.", author: "Colin Farrell, provavelmente irreconhecível debaixo de 4h de maquiagem" },
    tag: "séries",
  },
  {
    id: 75,
    title: "Demolidor (Netflix, 2015)",
    desc: "A Marvel deu pro Netflix um herói cego de segunda linha. Charlie Cox entregou uma das melhores séries de super-herói já feitas. Cena do corredor em plano-sequência é referência até hoje. Vincent D'Onofrio como Kingpin compete com vilão de HBO. Combou no Justiceiro do Jon Bernthal. Tão bom que a Disney tornou canon sem mudar NADA.",
    quote: { text: "I'm just trying to make my city a better place.", author: "Matt Murdock, provavelmente antes de quebrar a cara de todo mundo num corredor" },
    tag: "séries",
  },
  {
    id: 76,
    title: "Scooby-Doo on Zombie Island (1998)",
    desc: 'Era pra ser mais um Scooby-Doo direto pra vídeo. Do nada os monstros são REAIS, tem gente morrendo de verdade, e a trilha sonora vai de desenho infantil pra filme de terror sem pedir licença. "It\'s Terror Time Again" não tinha direito de existir num filme do Scooby.',
    quote: { text: "This time, the monsters are real.", author: "Tagline do filme que traumatizou uma geração" },
    tag: "cinema",
  },
  {
    id: 77,
    title: "What's New, Scooby-Doo? — abertura do Simple Plan",
    desc: "Chamaram a Simple Plan, banda de pop-punk no auge, pra fazer abertura de desenho infantil do Scooby-Doo. Entregaram um banger que até hoje é impossível de ouvir sem cantar junto. Banda de rock séria fazendo tema de cartoon e entregando mais que precisava. Pedem pra cantarem essa música em show até hoje.",
    quote: { text: "What's new, Scooby-Doo? We're coming after you!", author: "Simple Plan, provavelmente banda de rock séria cantando pra cachorro" },
    tag: "música",
  },
  {
    id: 78,
    title: "Shrek 2 — Holding Out for a Hero",
    desc: 'Sequel de filme de piada de peido sobre ogro verde. A cena do Gato de Botas invadindo o castelo ao som de "I Need a Hero" é uma das melhores sequências de ação da história da animação. Sequel cômica não tem direito de ter climax assim.',
    quote: { text: "I need a hero!", author: "Fada Madrinha, numa sequência que não precisava existir" },
    tag: "cinema",
  },
  {
    id: 79,
    title: "Trilogia do Senhor dos Anéis (2001-2003) — #100",
    desc: "O item #100 dessa lista. Eu não gosto, mas tenho que reconhecer. Diretor de FILME DE TERROR (Bad Taste, Braindead) fora da zona de conforto. Estúdio B-movie (New Line) arriscando falência. Filmado na NOVA ZELÂNDIA. TRÊS filmes simultâneos, 274 dias de filmagem. 48 mil peças de armadura feitas à mão. Atores quebraram dentes e dedos. 11 Oscars merecidos. Agradou fãs hardcore de Tolkien E gente que nunca leu o livro. Fez o impossível. Não precisava ser tão bom. Mas foi.",
    quote: { text: "I'm shooting this fucking film and I'm doing the best job I can.", author: "Peter Jackson, respondendo ao estúdio que ameaçou processá-lo no meio das filmagens" },
    tag: "cinema",
  },
];

const betrayals = [
  {
    id: 1,
    title: "True Detective (qualquer coisa pós-S1)",
    desc: "Mesmo criador, mesma HBO, mesmo formato. A S1 tinha McConaughey filosofando sobre o tempo ser um círculo plano enquanto caçava serial killers na Louisiana. Depois disso? Vince Vaughn falando frases que viraram meme por serem ruins e uma S3 que ninguém lembra.",
    quote: { text: "Never do anything out of hunger, not even eating.", author: "Frank Semyon, a frase que matou a série" },
    tag: "séries",
  },
  {
    id: 2,
    title: "Promised Neverland S2",
    desc: "A S1 era perfeita — tensão, estratégia, plot twists. A S2 PULOU ARCOS INTEIROS do mangá e no último episódio botou um SLIDESHOW com fotos do que TERIA SIDO a história. Literalmente PowerPoint. Mostraram as cenas que você QUERIA ver em formato de apresentação de slides.",
    quote: { text: "Vamos adaptar os melhores arcos do mangá? Não, bota um slideshow.", author: "CloverWorks, provavelmente" },
    tag: "séries",
  },
  {
    id: 3,
    title: "Berserk (2016/2017)",
    desc: "Literalmente O MAIOR MANGÁ DE DARK FANTASY JÁ ESCRITO. Obra-prima do Miura. Entregaram CGI de PS2 misturado com 2D aleatório a 12 frames por segundo. Guts, o personagem mais badass da ficção japonesa, andando como PowerPoint animado. Miura merecia mais.",
    quote: { text: "Vamos usar 2D ou 3D? — Sim.", author: "Diretor do anime, provavelmente escolhendo o pior dos dois mundos" },
    tag: "séries",
  },
  {
    id: 4,
    title: "One Punch Man S3 — 'One-Frame Man' (2025)",
    desc: "Esperaram 6 ANOS. A S1 da Madhouse era lendária — melhor animação de ação da década. A J.C. Staff entregou algo tão ruim que os fãs apelidaram de 'One-Frame Man'. O episódio 6 teve uma IMAGEM ESTÁTICA de 20 segundos de uma parede de prédio com voz por cima. Pior nota de anime na história do IMDb: 1.5. Cinco por cento no Rotten Tomatoes. O diretor desativou as redes sociais. Seis anos pra isso.",
    quote: { text: "One-Frame Man.", author: "Fãs, renomeando a série com base na quantidade de frames" },
    tag: "séries",
  },
  {
    id: 5,
    title: "O cavalo 3D de Apothecary Diaries",
    desc: "Anime com animação linda, cenários detalhados, figurinos históricos impecáveis. Do nada aparece um cavalo 3D de PS1 deslizando pela tela como se tivesse em cima de rodinhas invisíveis. Gastaram o orçamento inteiro nos kimonos e sobrou clip art pro cavalo.",
    quote: { text: "A gente tem budget pra animar o cavalo? — Bota ele em 3D que ninguém nota.", author: "Alguém que notaram, provavelmente" },
    tag: "séries",
  },
  {
    id: 6,
    title: "D&D 4ª Edição (2008)",
    desc: "Pegaram o RPG de mesa mais icônico da história e tentaram transformar num MMO de papel. Alienaram a fanbase inteira. Tão ruim que os fãs criaram a concorrência — Pathfinder nasceu porque a galera se recusou a migrar. Quando a 5e saiu, a Wizards of the Coast fingiu que a 4e nunca existiu. Literalmente o filho que a família não menciona no jantar.",
    quote: { text: "É basicamente World of Warcraft mas no papel e sem a parte divertida.", author: "Resumo de todo review da época, provavelmente" },
    tag: "games",
  },
  {
    id: 7,
    title: "Skull and Bones (2024)",
    desc: "A Ubisoft ACIDENTALMENTE fez o melhor jogo de pirata da história dentro de um Assassin's Creed. Aí pensou 'vamos fazer um de propósito agora'. Dez anos de desenvolvimento. Recomeçaram do zero 3 vezes. Quando saiu, ninguém lembrava que existia. Tentaram de propósito o que já tinham feito sem querer e falharam tão feio que o nome do jogo virou pergunta: 'como é que chamava mesmo?'",
    quote: { text: "Era tipo Black Flag mas sem o Assassin's Creed, sem a história, sem os shanties, e sem a diversão.", author: "Basicamente todo review, provavelmente" },
    tag: "games",
  },
  {
    id: 8,
    title: "Joker: Folie à Deux (2024)",
    desc: "O primeiro Joker ganhou Leão de Ouro e Oscar. A sequência? Um musical. Ninguém pediu musical. Ninguém queria musical. Joaquin Phoenix cantando desafinado enquanto Lady Gaga era subutilizada. Perdeu 200 milhões de dólares. Destruíram tudo que o primeiro construiu em 2 horas de karaokê triste.",
    quote: { text: "E se a gente fizesse uma continuação... MUSICAL?", author: "Todd Phillips, provavelmente destruindo o próprio legado" },
    tag: "cinema",
  },
  {
    id: 9,
    title: "Diablo Immortal (anúncio, 2018)",
    desc: "Ingresso da BlizzCon: $199. Voo pra Anaheim: ~$500. Hotel 2 noites: ~$400. Comida e merch: ~$200. Total: ~$1.300 pra ouvir um dev perguntar se você tem celular. Plateia inteira esperando Diablo 4. Anunciam jogo de celular. Silêncio. Vaias. 'Do you guys not have phones?' entra pra história como o momento mais caro e desconectado da indústria de games.",
    quote: { text: "Do you guys not have phones?", author: "Dev da Blizzard, segundos antes do desastre" },
    tag: "games",
  },
  {
    id: 10,
    title: "Final de Jujutsu Kaisen (mangá)",
    desc: "Uma das maiores séries de mangá da década. Gege Akutami decidiu speedrunnar o final — correu, não explicou nada, matou gente sem cerimônia. Depois lançou capítulo extra pra 'resolver' as pontas soltas. Não resolveu quase nada. A animação na aba 'Boas Demais' e o final aqui. Mesma série. Duas abas.",
    quote: { text: "E se eu correr no final, não explicar nada, e depois lançar um módulo pra não explicar quase mais nada?", author: "Gege Akutami, provavelmente exausto" },
    tag: "séries",
  },
  {
    id: 11,
    title: "U2 botando álbum no iTunes de todo mundo (2014)",
    desc: "A Apple e o U2 decidiram que 500 milhões de pessoas QUERIAM o álbum Songs of Innocence. Não perguntaram. Apareceu no celular de todo mundo. A reação foi tão negativa que a Apple teve que criar uma ferramenta específica só pra remover. Um botão literal de 'TIRE O U2 DO MEU CELULAR'. A maior banda de rock do mundo virando spam.",
    quote: { text: "Vocês vão adorar! — Ninguém adorou.", author: "Bono, provavelmente descobrindo que presente forçado não é presente" },
    tag: "música",
  },
  {
    id: 12,
    title: "Epic Games Store — 3 anos sem carrinho",
    desc: "Empresa bilionária do Fortnite lança loja pra competir com a Steam. Dá jogos grátis toda semana. Mas esqueceu de colocar... carrinho de compras. Uma LOJA ONLINE sem carrinho. Demorou 3 ANOS pra adicionar. O CEO comemorou no Twitter como se fosse inovação. Em 2021. Carrinho de compras. A feature que existe desde os anos 90 na internet.",
    quote: { text: "So, like, the Epic Games Store doesn't have a shopping cart. It ought to have a shopping cart. Someday it will have a shopping cart.", author: "Tim Sweeney, CEO da Epic, em 2021. Algum dia." },
    tag: "tech",
  },
  {
    id: 13,
    title: "Meta Metaverse (~$90 bilhões jogados fora)",
    desc: "Zuckerberg mudou o nome do Facebook, prometeu o futuro da humanidade, e entregou avatares sem pernas num Wii Sports de 2006. Galera esperando Nerve Gear do SAO e recebeu Second Life com gráfico pior. Com $90 bilhões ele podia ter: comprado a Nintendo inteira ($63B), financiado a NASA por 3 anos ($25B/ano), dado um Quest 3 DE GRAÇA pra 180 milhões de pessoas, comprado o Minecraft 36 vezes, ou construído uma cidade real. Escolheu fazer reunião de trabalho com Mii.",
    quote: { text: "Parece os mundos virtuais dos anos 90. Imagina a Renascença e as pessoas fazendo pintura de caverna.", author: "Celia Pearce, professora de Game Design" },
    tag: "tech",
  },
  {
    id: 14,
    title: "GPT-5 (2025)",
    desc: "Altman postou foto da Estrela da Morte antes do lançamento. Prometeu 'PhD-level expert em qualquer área'. Usuários odiaram tanto que a OpenAI restaurou o GPT-4o em 24 HORAS. Altman admitiu que 'totally screwed up'. O modelo não sabia contar os B's em 'blueberry'. O dia do lançamento foi apelidado de 'Gary Marcus Day'. ChatGPT na aba Boa e GPT-5 aqui. Mesma empresa. Duas abas.",
    quote: { text: "GPT-5 vai fazer o GPT-4 parecer levemente embaraçoso. — O GPT-4 foi restaurado em 24h.", author: "Sam Altman, antes e depois da realidade" },
    tag: "tech",
  },
  {
    id: 15,
    title: "Marvin Minsky — Perceptrons (1969)",
    desc: "Matematicamente PROVOU que um perceptron não resolvia XOR. Publicou o livro. Matou o funding de redes neurais por 15 ANOS. O primeiro AI Winter inteiro. Gerações de pesquisadores mudaram de área. Bilhões em pesquisa perdidos. A solução? Bota mais uma camada. Literalmente. Multi-layer perceptron. Alguém perguntou 'e se usar duas?' e desfez 15 anos de inverno. Um livro de 200 páginas atrasou a civilização porque ninguém tentou o óbvio.",
    quote: { text: "XOR é impossível com uma camada. — E se usar duas? — ...", author: "15 anos de silêncio entre a pergunta e a resposta" },
    tag: "tech",
  },
  {
    id: 16,
    title: "Mighty No. 9 (2016)",
    desc: "O CRIADOR DO MEGA MAN faz Kickstarter pra fazer o 'novo Mega Man'. Levanta quase $4 milhões. Atrasa várias vezes. Sai bugado e medíocre. Os créditos são maiores que o jogo de tanta gente que pagou pra financiar essa bomba. O trailer tinha a frase 'make the bad guys cry like an anime fan on prom night'. O jogo fez os BACKERS chorarem.",
    quote: { text: "It's better than nothing. — Congrats on the launch! It's better than nothing.", author: "Livestream oficial do jogo / Sonic the Hedgehog zoando no Twitter" },
    tag: "games",
  },
  {
    id: 17,
    title: "OUYA (2013)",
    desc: "O console que ia 'democratizar os games'. Levantou $8.5 milhões no Kickstarter, maior campanha de games da história na época. Prometeram o console indie definitivo por $99. Chegou com controle horrível, loja vazia, hardware de celular Android barato num cubo. Morreu em menos de 2 anos. Hoje é literalmente peso de porta e piada em lista de fracassos. O PS2 na aba Boa e o OUYA aqui. A diferença entre fazer um console bom demais sem querer e tentar fazer um de propósito e falhar.",
    quote: { text: "A beautiful brick.", author: "Review da época, provavelmente" },
    tag: "tech",
  },
  {
    id: 18,
    title: "No Man's Sky no lançamento (2016)",
    desc: "Sean Murray prometeu o universo. Literalmente. Multiplayer, planetas infinitos, fauna única. Lançou vazio, sem quase nada do prometido. MAS plot twist raro: em vez de fugir com o dinheiro, ele CALOU A BOCA, trabalhou 8 anos sem dar entrevista, e hoje o jogo é EXATAMENTE o que prometeram e mais. É a única traição nessa lista com arco de redenção. Respeito relutante.",
    quote: { text: "Não vou falar mais nada. Vou só trabalhar.", author: "Sean Murray, provavelmente calado por anos enquanto consertava tudo" },
    tag: "games",
  },
  {
    id: 19,
    title: "Luciano Huck como Flynn Rider em Enrolados",
    desc: "A Disney tinha o Guilherme Briggs, o Bussunda, uma geração INTEIRA de dubladores lendários no Brasil. Escolheram um apresentador de TV pra dublar o protagonista galã da Rapunzel. Marketing puro. Atuação dura, voz que não combina, enquanto do outro lado da parede o Briggs tava fazendo milagre com qualquer personagem. Bussunda e Briggs na aba Boa. Huck aqui. A dualidade da dublagem brasileira.",
    quote: { text: "Quem quer dinheiro?", author: "Luciano Huck, provavelmente o motivo real da escalação" },
    tag: "dub",
  },
  {
    id: 20,
    title: "Pitty como Cassie Cage em Mortal Kombat X",
    desc: "A Warner escalou a cantora de rock Pitty pra dublar Cassie Cage no Mortal Kombat X. Foi tão ruim que os fãs fizeram uma PETIÇÃO com 8 mil assinaturas pedindo um patch de REDUBLAGEM. Petição. Pra redublar. A coitada falou 'fiz o melhor possível'. A culpa é da Warner que acha que celebridade = dublador. Huck e Pitty lado a lado nos traidores. A Warner não aprende.",
    quote: { text: "Fiz o melhor possível.", author: "Pitty, sobre 8 mil pessoas pedindo pra apagar seu trabalho" },
    tag: "dub",
  },
];

const meh = [
  {
    id: 1,
    title: "Windows depois do 7",
    desc: "Você PAGA pelo sistema operacional. Ele te mostra propaganda do Bing. Você pesquisa 'calculadora' na barra de iniciar e ele abre o Edge te pedindo pra tornar padrão. O Edge que você não instalou te perguntando se você quer ele. Toda vez. Pra sempre. Você comprou adware com interface bonita. O Windows 7 era o último que te respeitava como ser humano.",
    quote: { text: "Procurei calculadora e abriu o Bing no Edge. Ambos me pedindo pra tornar padrão. Valeu mesmo, Microsoft.", author: "Todo usuário de Windows, diariamente" },
    tag: "tech",
  },
];

// Ordem determina cor/ordem dos filtros. Valores são mapeados em styles.css via [data-tag="..."].
const tagColors = {
  games: "#e94560",
  "música": "#f5a623",
  cinema: "#50fa7b",
  "séries": "#bd93f9",
  dub: "#8be9fd",
  tech: "#ff79c6",
};

const allTags = ["todos", ...Object.keys(tagColors)];
